In [1]:
test_input = """...#......
.......#..
#.........
..........
......#...
.#........
.........#
..........
.......#..
#...#....."""

input = open("inputs/11").read()

In [2]:
import numpy as np

def parse_board(input):
    return list(map(list, input.splitlines()))

In [3]:
# board = np.array(parse_board(test_input))
board = np.array(parse_board(input))
board

array([['.', '.', '.', ..., '.', '.', '.'],
       ['.', '.', '.', ..., '.', '.', '.'],
       ['.', '#', '.', ..., '.', '.', '.'],
       ...,
       ['.', '.', '.', ..., '#', '.', '.'],
       ['#', '.', '.', ..., '.', '.', '.'],
       ['.', '.', '.', ..., '.', '.', '.']], dtype='<U1')

In [4]:
binary_board = (board == '#').astype(int)
binary_board

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 1, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [5]:
column_sums = binary_board.sum(axis=0)
row_sums = binary_board.sum(axis=1)

In [6]:
empty_rows = np.where(row_sums == 0)[0]
empty_cols = np.where(column_sums == 0)[0]

In [7]:
empty_rows, empty_cols

(array([ 16,  53,  57,  58,  60,  78,  91, 130]),
 array([ 24,  46,  55,  73,  74,  80,  84,  89, 113, 117, 135]))

In [8]:
galaxy_row_idxs, galaxy_col_idxs = np.where(binary_board)

In [9]:
# empty_replacement_factor = 2
# empty_replacement_factor = 10
# empty_replacement_factor = 100
empty_replacement_factor = 1000000

In [10]:
row_offsets = (galaxy_row_idxs > empty_rows[:, None]).sum(axis=0) * (empty_replacement_factor - 1)
col_offsets = (galaxy_col_idxs > empty_cols[:, None]).sum(axis=0) * (empty_replacement_factor - 1)

In [12]:
expanded_galaxy_row_idxs = row_offsets + galaxy_row_idxs
expanded_galaxy_col_idxs = col_offsets + galaxy_col_idxs

In [13]:
import itertools


s = 0

for (p1, p2) in itertools.combinations(zip(expanded_galaxy_row_idxs, expanded_galaxy_col_idxs), 2):
    d = abs(p1[0] - p2[0]) + abs(p1[1] - p2[1])
    s += d

In [14]:
s

702152204842