In [1]:
test_input = """19, 13, 30 @ -2,  1, -2
18, 19, 22 @ -1, -1, -2
20, 25, 34 @ -2, -2, -4
12, 31, 28 @ -1, -2, -1
20, 19, 15 @  1, -5, -3"""

In [2]:
input = open("inputs/24").read()

In [3]:
input_rays = []

# for l in test_input.splitlines():
for l in input.splitlines():
    initial, dir = l.split(" @ ")

    initial = [int(x) for x in initial.split(", ")]
    dir = [int(x) for x in dir.split(", ")]

    input_rays.append((initial, dir))

In [4]:
input_rays

[([364193859817003, 337161998875178, 148850519939119], [85, 85, 473]),
 ([222402516161891, 289638719990878, 261939904566871], [123, -40, 25]),
 ([219626703416113, 76777384100180, 165418060594769], [115, 317, 193]),
 ([334014037912851, 277570220219582, 209375720159907], [-121, -80, 116]),
 ([287190980765131, 255535497710972, 312523085347417], [109, 124, -140]),
 ([234886861358651, 242049831142762, 284674462721087], [30, -13, 12]),
 ([318123114620241, 57779289415022, 104021426110157], [38, 649, 396]),
 ([414924365272846, 347098380764754, 274815913131088], [-212, -85, -76]),
 ([178659733911043, 235997257427522, 329124085782047], [44, -46, -19]),
 ([305237792764107, 250686948592234, 309852066718257], [-19, 35, -64]),
 ([273597981930275, 440308709640186, 469786981522303], [32, -307, -343]),
 ([408324200512731, 406186314332306, 243659676144735], [-57, -434, -335]),
 ([353587787512041, 133063636294234, 291877578038455], [-102, 267, -37]),
 ([381538409034485, 424997194110414, 537617243846654],

In [5]:
va = (-1, -1, -2)
vb = (-2, -2, -4)

same_direction = all(a / b == va[0] / vb[0] for a, b in zip(va, vb))

In [6]:
# get 2d point slope form 
from dataclasses import dataclass
from typing import Tuple


# @dataclass
# class Ray:
#     initial: Tuple[int, int]
#     direction: Tuple[int, int]
#     slope: float
#     coeffs: Tuple[float, float]
#     b: float


In [7]:
# MIN_COORD = 7
# MAX_COORD = 27

MIN_COORD = 200000000000000
MAX_COORD = 400000000000000

In [8]:
import itertools
import numpy as np

s = 0

for (ra, va), (rb, vb) in itertools.combinations(input_rays, 2):
    ra = np.array(ra[:2])
    va = np.array(va[:2])
    rb = np.array(rb[:2])
    vb = np.array(vb[:2])

    same_direction = all(a / b == va[0] / vb[0] for a, b in zip(va, vb))

    if same_direction:
        print("Same direction")
        continue

    A = np.array([va, -vb]).T
    b = rb - ra

    t_a, t_b = np.linalg.solve(A, b)

    if t_a < 0 or t_b < 0:
        print("Backwards in time")
        continue

    x_h = ra[0] + t_a * va[0]
    y_h = ra[1] + t_a * va[1]

    if x_h < MIN_COORD or x_h > MAX_COORD or y_h < MIN_COORD or y_h > MAX_COORD:
        print("Out of bounds")
        continue

    s += 1

s

Backwards in time
Backwards in time
Backwards in time
Backwards in time
Backwards in time
Backwards in time
Backwards in time
Backwards in time
Backwards in time
Backwards in time
Out of bounds
Backwards in time
Backwards in time
Backwards in time
Backwards in time
Backwards in time
Backwards in time
Backwards in time
Backwards in time
Backwards in time
Backwards in time
Backwards in time
Backwards in time
Backwards in time
Backwards in time
Backwards in time
Backwards in time
Backwards in time
Backwards in time
Backwards in time
Backwards in time
Backwards in time
Backwards in time
Backwards in time
Backwards in time
Backwards in time
Backwards in time
Backwards in time
Backwards in time
Backwards in time
Backwards in time
Backwards in time
Backwards in time
Backwards in time
Backwards in time
Backwards in time
Backwards in time
Backwards in time
Backwards in time
Backwards in time
Backwards in time
Backwards in time
Backwards in time
Backwards in time
Backwards in time
Backwards in t

17244

In [9]:
234886861358651 // 30

7829562045288

In [10]:
from sympy import divisors

In [11]:
# m = 29
# k = 30

# m = 5
# k = 27

# m = 2
# k = 294
m = 0
k = 1

r1, v1 = input_rays[m]
r2, v2 = input_rays[k]

r1, v1 = np.array(r1), np.array(v1)
r2, v2 = np.array(r2), np.array(v2)

r1 - r2

array([ 141791343655112,   47523278884300, -113089384627752])

In [12]:
for t1 in range(1000):
    test = r1 - r2 + t1*(v1 - v2)
    print(test)

    divisor_sets = [divisors(x) for x in test]
    divisor_intersection = list(sorted(set.intersection(*[set(d) for d in divisor_sets])))

    print(t1)
    print(divisor_intersection)
    print()

[ 141791343655112   47523278884300 -113089384627752]
0
[1, 2, 4]

[ 141791343655074   47523278884425 -113089384627304]
1
[1]

[ 141791343655036   47523278884550 -113089384626856]
2
[1, 2]

[ 141791343654998   47523278884675 -113089384626408]
3
[1]

[ 141791343654960   47523278884800 -113089384625960]
4
[1, 2, 4, 5, 8, 10, 20, 40]

[ 141791343654922   47523278884925 -113089384625512]
5
[1]

[ 141791343654884   47523278885050 -113089384625064]
6
[1, 2]

[ 141791343654846   47523278885175 -113089384624616]
7
[1]

[ 141791343654808   47523278885300 -113089384624168]
8
[1, 2, 4]

[ 141791343654770   47523278885425 -113089384623720]
9
[1, 5]

[ 141791343654732   47523278885550 -113089384623272]
10
[1, 2, 53, 106]

[ 141791343654694   47523278885675 -113089384622824]
11
[1]

[ 141791343654656   47523278885800 -113089384622376]
12
[1, 2, 4, 8]

[ 141791343654618   47523278885925 -113089384621928]
13
[1]

[ 141791343654580   47523278886050 -113089384621480]
14
[1, 2, 5, 10]

[ 141791343654542  

In [13]:

# divisor_sets = []

# for a in r1-r2:
#     d = divisors(np.abs(a))
#     print(d)
#     divisor_sets.append(d)

# divisor_intersection = set.intersection(*[set(d) for d in divisor_sets])

In [14]:
min([r[0] for r, v in input_rays]), max([r[0] for r, v in input_rays])

(7209485524853, 496351863424555)

In [15]:
import pandas as pd

# df = pd.DataFrame(input_rays, columns=["r", "v"])
rows = []

for r, v in input_rays:
    rows.append({"r0": r[0], "r1": r[1], "r2": r[2], "v0": v[0], "v1": v[1], "v2": v[2]})

df = pd.DataFrame(rows)

df

r0               r1               r2   v0   v1   v2
0    364193859817003  337161998875178  148850519939119   85   85  473
1    222402516161891  289638719990878  261939904566871  123  -40   25
2    219626703416113   76777384100180  165418060594769  115  317  193
3    334014037912851  277570220219582  209375720159907 -121  -80  116
4    287190980765131  255535497710972  312523085347417  109  124 -140
..               ...              ...              ...  ...  ...  ...
295  356217954556966  361580921545642  447680337795922  -92 -157 -386
296  210698356285555  182596207883186  102071280428192  -11   -5  226
297  353707675498172  279424144802785  281131132911930  -58   66  -62
298  175333305826996  224300669373432  292157412768897  214   81  -31
299  409810530260833  330082954692680  262659891151901 -206  -92    8

[300 rows x 6 columns]

In [16]:
df.sort_values("r0").head(3)

r0               r1               r2   v0   v1   v2
180   7209485524853   52423663169760  307419819862807  212  140   11
269  10868238730187  309748079927666  120290341070415  177 -140  203
282  14805605333923   64297940155954  125742764015035  295  201  224

In [17]:
df.sort_values("r0", ascending=False).head(3)

r0               r1               r2   v0   v1   v2
199  496351863424555  497673967198826  429202379353967 -344 -383 -219
167  485364518290031  454454553722316  495142085314989 -297 -288 -190
195  444649061161123  335946089222300  308492168075963 -263 -140  -27

In [18]:
df.sort_values("r1").head(3)

r0              r1               r2   v0   v1  v2
89   62964016039966  40021647758927  336399289616972  188  188 -32
42   28075495353370  48134605214405  337532387891225  196  150 -23
180   7209485524853  52423663169760  307419819862807  212  140  11

In [19]:
df.sort_values("r2", ascending=False).head(3)

r0               r1               r2   v0   v1   v2
170  328919745563896  279793536536927  556116718239587  -54   -8 -541
205  415236437730235  267212668416410  550127542617695 -221  -59 -327
13   381538409034485  424997194110414  537617243846654 -121 -313 -786

In [20]:
import itertools
from sympy import symbols, Eq, solve, Symbol

n = len(input_rays)

x_symbols = symbols(f'x0:{n}')
y_symbols = symbols(f'y0:{n}')
z_symbols = symbols(f'z0:{n}')

v_x_hat = Symbol('v_x_hat', integer=True)
v_y_hat = Symbol('v_y_hat', integer=True)
v_z_hat = Symbol('v_z_hat', integer=True)

# Create a list to hold all equations
equations = []

for i, (r, v) in enumerate(input_rays):
    eq1 = Eq((x_symbols[i] - r[0])/v[0], (y_symbols[i] - r[1])/v[1])
    eq2 = Eq((x_symbols[i] - r[0])/v[0], (z_symbols[i] - r[2])/v[2])
    eq3 = Eq((y_symbols[i] - r[1])/v[1], (z_symbols[i] - r[2])/v[2])

    equations.append(eq1)
    equations.append(eq2)
    equations.append(eq3)

pairs = list(itertools.combinations(range(n), 2))

to_sample = min(32, len(pairs))
sampled_pairs = np.random.choice(np.arange(len(pairs)), to_sample, replace=False)

for p in sampled_pairs:
    i, j = pairs[p]
    eq1 = Eq((x_symbols[i] - x_symbols[j])/v_x_hat, (y_symbols[i] - y_symbols[j])/v_y_hat)
    eq2 = Eq((x_symbols[i] - x_symbols[j])/v_x_hat, (z_symbols[i] - z_symbols[j])/v_z_hat)
    eq3 = Eq((y_symbols[i] - y_symbols[j])/v_y_hat, (z_symbols[i] - z_symbols[j])/v_z_hat)

    equations.append(eq1)
    equations.append(eq2)
    equations.append(eq3)


# solutions = solve(equations, x_symbols + y_symbols + z_symbols + (v_x_hat, v_y_hat, v_z_hat))
# solutions

In [21]:
# equations.append(Eq((y_symbols[1] - y_symbols[0]) * (x_symbols[2] - x_symbols[1]) - (x_symbols[1] - x_symbols[0]) * (y_symbols[2] - y_symbols[1]), 0))
# equations.append(Eq((z_symbols[1] - z_symbols[0]) * (x_symbols[2] - x_symbols[1]) - (x_symbols[1] - x_symbols[0]) * (z_symbols[2] - z_symbols[1]), 0))
# equations.append(Eq((z_symbols[1] - z_symbols[0]) * (x_symbols[2] - x_symbols[1]), (x_symbols[1] - x_symbols[0]) * (z_symbols[2] - z_symbols[1])))

In [22]:
from z3 import Real, Solver, And, sat, Int, Not, set_param
import numpy as np
import itertools

n = len(input_rays)
# n = 20
# n = 10
# n = 50
# n = 75

# Defining Z3 variables
x_vars = [Real(f'x_{i}') for i in range(n)]
y_vars = [Real(f'y_{i}') for i in range(n)]
z_vars = [Real(f'z_{i}') for i in range(n)]

v_x_hat = Int('v_x_hat')
v_y_hat = Int('v_y_hat')
v_z_hat = Int('v_z_hat')

# Z3 solver
solver = Solver()

# Add non-zero constraints
solver.add(Not(v_x_hat == 0))
solver.add(Not(v_y_hat == 0))
solver.add(Not(v_z_hat == 0))

# Translating SymPy equations to Z3
for i, (r, v) in enumerate(input_rays[:n]):
    solver.add((x_vars[i] - r[0])/v[0] == (y_vars[i] - r[1])/v[1])
    solver.add((x_vars[i] - r[0])/v[0] == (z_vars[i] - r[2])/v[2])
    solver.add((y_vars[i] - r[1])/v[1] == (z_vars[i] - r[2])/v[2])

# Generating all possible pairs
pairs = list(itertools.combinations(range(n), 2))
print(n, len(pairs))
# Randomly sample pairs
# sampled_pairs = np.random.choice(np.arange(len(pairs)), 500, replace=False)
sampled_pairs = np.random.choice(np.arange(len(pairs)), 10, replace=False)

# Pairwise comparisons for sampled pairs
for p in sampled_pairs:
# for p in range(len(pairs)):
    i, j = pairs[p]

    solver.add( ((y_vars[i] - y_vars[j]) * v_x_hat) == ((x_vars[i] - x_vars[j]) * v_y_hat) )
    solver.add( ((z_vars[i] - z_vars[j]) * v_x_hat) == ((x_vars[i] - x_vars[j]) * v_z_hat) )
    solver.add( ((z_vars[i] - z_vars[j]) * v_y_hat) == ((y_vars[i] - y_vars[j]) * v_z_hat) )

# Check if the system is solvable
if solver.check() == sat:
    model = solver.model()
    # return model
else:
    # return "No solution found"
    pass

model

300 44850


NameError: name 'model' is not defined

In [ ]:
model.evaluate(v_x_hat), model.evaluate(v_y_hat), model.evaluate(v_z_hat)

In [ ]:
v_hat = np.array([model.evaluate(v_x_hat).as_long(), model.evaluate(v_y_hat).as_long(), model.evaluate(v_z_hat).as_long()])
v_hat

In [ ]:
x_0, y_0, z_0 = model.evaluate(x_vars[0]), model.evaluate(y_vars[0]), model.evaluate(z_vars[0])
hit_0 = np.array([x_0.as_long(), y_0.as_long(), z_0.as_long()])
hit_0

In [ ]:
r_0, v_0 = np.array(input_rays[0][0]), np.array(input_rays[0][1])
r_0, v_0

In [ ]:
t0 = (hit_0 - r_0) / v_0

assert np.allclose(t0, t0[0])

t0 = t0[0]

t0

In [ ]:
r_hat = (hit_0 - t0 * v_hat).astype(np.int64)
r_hat[0], r_hat[1], r_hat[2], sum(r_hat)

In [ ]:
# 544104164915716 too low?
# 904791039119044 too low?

In [26]:
from z3 import Real, Solver, sat, Int, Not

# n = len(input_rays)
n = 3

random_input_array_idxs = np.random.choice(np.arange(len(input_rays)), n, replace=False)
# print(random_input_array_idxs)

t_vars = [Real(f'x_{i}') for i in range(n)]

v_x_hat = Int('v_x_hat')
v_y_hat = Int('v_y_hat')
v_z_hat = Int('v_z_hat')

r_x_hat = Int('r_x_hat')
r_y_hat = Int('r_y_hat')
r_z_hat = Int('r_z_hat')

solver = Solver()

solver.add(Not(v_x_hat == 0))
solver.add(Not(v_y_hat == 0))
solver.add(Not(v_z_hat == 0))

for t in t_vars:
    solver.add(t > 0)

# for i, (r, v) in enumerate(input_rays[:n]):
for i, (r, v) in enumerate([input_rays[j] for j in random_input_array_idxs]):
    solver.add(r_x_hat + v_x_hat * t_vars[i] == r[0] + v[0] * t_vars[i])
    solver.add(r_y_hat + v_y_hat * t_vars[i] == r[1] + v[1] * t_vars[i])
    solver.add(r_z_hat + v_z_hat * t_vars[i] == r[2] + v[2] * t_vars[i])

if solver.check() == sat:
    model = solver.model()
else:
    model = None

model

In [ ]:
model.evaluate(r_x_hat).as_long() + model.evaluate(r_y_hat).as_long() + model.evaluate(r_z_hat).as_long()

In [38]:
import itertools
from sympy import symbols, Eq, solve, Symbol

# n = len(input_rays)
n = 3

t_symbols = symbols(f't0:{n}', positive=True)

v_x_hat = Symbol('v_x_hat', integer=True)
v_y_hat = Symbol('v_y_hat', integer=True)
v_z_hat = Symbol('v_z_hat', integer=True)

r_x_hat = Symbol('r_x_hat', integer=True)
r_y_hat = Symbol('r_y_hat', integer=True)
r_z_hat = Symbol('r_z_hat', integer=True)

# Create a list to hold all equations
equations = []

for i, (r, v) in enumerate(input_rays[:n]):
    eq1 = Eq(r_x_hat + v_x_hat * t_symbols[i], r[0] + v[0] * t_symbols[i])
    eq2 = Eq(r_y_hat + v_y_hat * t_symbols[i], r[1] + v[1] * t_symbols[i])
    eq3 = Eq(r_z_hat + v_z_hat * t_symbols[i], r[2] + v[2] * t_symbols[i])

    equations.append(eq1)
    equations.append(eq2)
    equations.append(eq3)

solutions = solve(equations, t_symbols + (v_x_hat, v_y_hat, v_z_hat) + (r_x_hat, r_y_hat, r_z_hat))
solutions

[(178381243424,
  564132261724,
  585444749559,
  -227,
  -221,
  111,
  419848807765291,
  391746659362922,
  213424530058607)]

In [40]:
equations

[Eq(r_x_hat + t0*v_x_hat, 85*t0 + 364193859817003),
 Eq(r_y_hat + t0*v_y_hat, 85*t0 + 337161998875178),
 Eq(r_z_hat + t0*v_z_hat, 473*t0 + 148850519939119),
 Eq(r_x_hat + t1*v_x_hat, 123*t1 + 222402516161891),
 Eq(r_y_hat + t1*v_y_hat, 289638719990878 - 40*t1),
 Eq(r_z_hat + t1*v_z_hat, 25*t1 + 261939904566871),
 Eq(r_x_hat + t2*v_x_hat, 115*t2 + 219626703416113),
 Eq(r_y_hat + t2*v_y_hat, 317*t2 + 76777384100180),
 Eq(r_z_hat + t2*v_z_hat, 193*t2 + 165418060594769)]

In [39]:
sum(solutions[0][-3:])

1025019997186820