In [1]:
test_input = """30373
25512
65332
33549
35390"""

In [2]:
import numpy as np
import pandas as pd

In [21]:
# grid = np.array([[int(i) for i in l] for l in test_input.split()])
grid = np.array([[int(i) for i in l] for l in open("inputs/8").read().split()])

In [22]:
grid

array([[2, 0, 0, ..., 1, 2, 1],
       [1, 2, 0, ..., 2, 2, 0],
       [0, 0, 1, ..., 2, 1, 1],
       ...,
       [1, 1, 0, ..., 0, 0, 0],
       [0, 2, 0, ..., 2, 0, 0],
       [1, 0, 0, ..., 1, 0, 2]])

In [23]:
grid_pd = pd.DataFrame(grid)

In [24]:
# take the top direction for starters.
# I know I can do this with cummax in a sec. i'll do this first

np.array(grid_pd.cummax(axis=0))

array([[2, 0, 0, ..., 1, 2, 1],
       [2, 2, 0, ..., 2, 2, 1],
       [2, 2, 1, ..., 2, 2, 1],
       ...,
       [5, 5, 5, ..., 5, 5, 5],
       [5, 5, 5, ..., 5, 5, 5],
       [5, 5, 5, ..., 5, 5, 5]])

In [25]:
grid.shape

(99, 99)

In [47]:
N = grid.shape[0]

def vis(a):
    return np.array([a[i] > (a[:i].max(axis=0) if i > 0 else -1) for i in range(N)])

In [50]:
top = vis(grid)
left = vis(grid.T).T

bottom = vis(grid[::-1])[::-1]
right = vis(grid[:, ::-1].T).T[:, ::-1]

In [51]:
# 1792
(top | left | bottom | right).sum()

1792

In [29]:
grid

array([[2, 0, 0, ..., 1, 2, 1],
       [1, 2, 0, ..., 2, 2, 0],
       [0, 0, 1, ..., 2, 1, 1],
       ...,
       [1, 1, 0, ..., 0, 0, 0],
       [0, 2, 0, ..., 2, 0, 0],
       [1, 0, 0, ..., 1, 0, 2]])

In [39]:
def index_first_true(a):
    return next((i+1 for i, v in enumerate(a) if v), len(a))

In [40]:
right_space = np.zeros_like(grid)
left_space = np.zeros_like(grid)
above_space = np.zeros_like(grid)
below_space = np.zeros_like(grid)

# just do right direction for simplicity
for (i, j), v in np.ndenumerate(grid):
    left_space[i, j] = index_first_true(grid[i, :j][::-1] >= v)
    right_space[i, j] = index_first_true(grid[i, (j+1):] >= v)

    above_space[i, j] = index_first_true(grid[:i, j][::-1] >= v)
    below_space[i, j] = index_first_true(grid[(i+1):, j] >= v)

In [42]:
# 334880
(left_space * right_space * above_space * below_space).max()

334880